baseURL = 'https://mirror.jazzofjapan.com/'
locale = 'en-us'
title = 'Mirror'
paginate = 300
theme = "PaperMod"

[params]
  [cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false
